### ISSUE TITLE
[L]Pseudo-code example of file adapter that using Replication SDK

### ISSUE THREAD

**Issue by knazarov** [NilFoundation/dbms-replication#9]
Write example of file adapter that use replication sdk. This example show main step of each protocol and how they can be mapping on replication sdk. 
This include:

- [x] Describe protocol of file adapter (similar to some market with transactions)
- [x] Set configurable variables
- [x] Load from some snapshot
- [x] Mapping protocol to DBMS operations
- [x] Write WALs into SDK
- [x] Read WALs

**Comment by Zerg1996** [comment]
Description file adapter can be found [here](https://www.notion.so/nilfoundation/File-adapter-example-5826fcec100d4de2a38efa6e92025767) and pseudo-code implementation [here](https://github.com/NilFoundation/database-research/pull/6)
